"use client";

// import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";
import { usePathname } from "next/navigation";
import { motion } from "framer-motion";
import { ConfigProvider } from 'antd';
import esES from 'antd/lib/locale/es_ES';
import { Toaster } from "react-hot-toast";

// Importa los estilos de Ant Design
import 'antd/dist/reset.css';

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  
  return (
    <html lang="es">
      <body>
        <ConfigProvider
          locale={esES}
          theme={{
            token: {
              fontFamily: "'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
            },
          }}
        >
          <motion.div
            key={pathname}
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -20 }}
            transition={{ duration: 0.3 }}
          >
            {children}
            <Toaster />
          </motion.div>
        </ConfigProvider>
      </body>
    </html>
  );
}
